# Generated by Django 5.2.1 on 2025-05-11 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="reading_history",
        ),
        migrations.CreateModel(
            name="UserArticleInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("is_bookmarked", models.BooleanField(default=False)),
                ("is_liked", models.BooleanField(default=False)),
                ("is_disliked", models.BooleanField(default=False)),
                ("date_interacted", models.DateTimeField(auto_now_add=True)),
                (
                    "interaction_type",
                    models.CharField(choices=[("click", "Click")], max_length=10),
                ),
                ("interacted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="news.article"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "article")},
            },
        ),
    ]
