# Generated by Django 5.2.1 on 2025-05-12 06:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_remove_userprofile_reading_history_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userarticleinteraction",
            name="is_bookmarked",
        ),
        migrations.RemoveField(
            model_name="userarticleinteraction",
            name="is_disliked",
        ),
        migrations.RemoveField(
            model_name="userarticleinteraction",
            name="is_liked",
        ),
        migrations.RemoveField(
            model_name="userarticleinteraction",
            name="is_read",
        ),
        migrations.AlterField(
            model_name="userarticleinteraction",
            name="interaction_type",
            field=models.CharField(
                choices=[
                    ("click", "Click"),
                    ("like", "Like"),
                    ("bookmark", "Bookmark"),
                    ("dislike", "Dislike"),
                ],
                max_length=10,
            ),
        ),
    ]
