# Generated by Django 5.2.1 on 2025-05-12 06:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0003_remove_userarticleinteraction_is_bookmarked_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userarticleinteraction",
            unique_together={("user", "article", "interaction_type")},
        ),
    ]
